services:

  - type: web

    name: smartfoods-backend

    env: node

    plan: free

    buildCommand: cd server && npm install

    startCommand: cd server && npm run dev

    envVars:

      - key: NODE_VERSION

        value: 18
